name: Build lmi Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 unzip

    - name: Setup proton-clang toolchain
      run: |
        mkdir -p $HOME/proton-clang
        cd $HOME/proton-clang
        wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
        unzip 20210522.zip
        rm 20210522.zip

    - name: Sync source
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/7a72/kernel_xiaomi_sm8250_mod --depth 1 kernel
        sed -i 's/CONFIG_LOCALVERSION="-perf"/CONFIG_LOCALVERSION="-zsck"/g' kernel/arch/arm64/configs/lmi_defconfig

    - name: Build kernel for lmi
      run: |
        cd $GITHUB_WORKSPACE/kernel
        KBUILD_BUILD_USER=7a72 KBUILD_BUILD_HOST=action bash build.sh lmi all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lmi-ksu-kernel
        path: |
          kernel/*.zip
